import Room1 from './HomeImg/HotelR1.jpeg'
import Room2 from './HomeImg/HotelR2.jpeg'
import Room3 from './HomeImg/HotelR3.jpeg'
import Room4 from './HomeImg/HotelR4.jpeg'
import Room5 from './HomeImg/HotelR5.jpeg'
import Room6 from './HomeImg/HotelR6.jpeg'
import Room7 from './HomeImg/HotelR7.jpeg'
import Room8 from './HomeImg/HotelR8.jpeg'
import Room9 from './HomeImg/HotelR9.jpeg'
import Room10 from './HomeImg/HotelR10.jpeg'

const RoomData  = [
    {
        id: 1,
        Avatar: Room1 ,
        name:" Luxury room1 ",
        desc: "A well furnished Apartment that suite you",
        price: 15000,
        state: "Lagos",
        city: "Ajegunle",
    },
    {
        id: 2,
        Avatar: Room2 ,
        name:" Luxury room2 ",
        desc: "A well furnished Apartment that suite you",
        price: 15000,
        state: "Lagos",
        city: "Ojuelegba",
    },
    {
        id: 3,
        Avatar: Room3 ,
        name:" Luxury  room3",
        desc: "A well furnished Apartment that suite you",
        price: 15000,
        state: "Lagos",
        city: "Lekki",
    },
    {
        id: 4,
        Avatar: Room4 ,
        name:" Luxury room4 ",
        desc: "A well furnished Apartment that suite you",
        price: 15000,
        state: "Ibadan",
        city: "Moniya",
    },
    {
        id: 5,
        Avatar: Room5 ,
        name:" Luxury room5 ",
        desc: "A well furnished Apartment that suite you",
        price: 15000,
        state: "Kwara",
        city: "Tanke",
    },
    {
        id: 6,
        Avatar: Room6 ,
        name:" Luxury room6 ",
        desc: "A well furnished Apartment that suite you",
        price: 15000,
        state: "Ibadan",
        city: "Post Office",
    },
    {
        id: 7,
        Avatar: Room7 ,
        name:" Luxury room7 ",
        desc: "A well furnished Apartment that suite you",
        price: 15000,
        state: "Lagos",
        city: "Orege wilmer",
    },
    {
        id: 8,
        Avatar: Room8 ,
        name:" Luxury room8 ",
        desc: "A well furnished Apartment that suite you",
        price: 15000,
        state: "Port-Harcourt",
        city: "Safele",
    },
    {
        id: 9,
        Avatar: Room9 ,
        name:" Luxury room9 ",
        desc: "A well furnished Apartment that suite you",
        price: 15000,
        state: "Abuja",
        city: "Gwagwalada",
    },
    {
        id: 10,
        Avatar: Room10 ,
        name:" Luxury room10 ",
        desc: "A well furnished Apartment that suite you",
        price: 15000,
        state: "Ibadan",
        city: "Round-About",
    },
    {
        id: 11,
        Avatar: Room1 ,
        name:" Luxury room1 ",
        desc: "A well furnished Apartment that suite you",
        price: 15000,
        state: "Lagos",
        city: "Ajegunle",
    },
    {
        id: 12,
        Avatar: Room2 ,
        name:" Luxury room2 ",
        desc: "A well furnished Apartment that suite you",
        price: 15000,
        state: "Lagos",
        city: "Ajegunle",
    },
    {
        id: 13,
        Avatar: Room3 ,
        name:" Luxury  room3",
        desc: "A well furnished Apartment that suite you",
        price: 15000,
        state: "Niger",
        city: "Mokwa",
    },
    {
        id: 14,
        Avatar: Room4 ,
        name:" Luxury room4 ",
        desc: "A well furnished Apartment that suite you",
        price: 15000,
        state: "Osun",
        city: "Modakeke",
    },
    {
        id: 15,
        Avatar: Room5 ,
        name:" Luxury room5 ",
        desc: "A well furnished Apartment that suite you",
        price: 15000,
        state: "Lagos",
        city: "Ajegunle",
    },
    {
        id: 16,
        Avatar: Room6 ,
        name:" Luxury room6 ",
        desc: "A well furnished Apartment that suite you",
        price: 15000,
        state: "Osun",
        city: "Ede",
    },
    {
        id: 17,
        Avatar: Room7 ,
        name:" Luxury room7 ",
        desc: "A well furnished Apartment that suite you",
        price: 15000,
        state: "Osun",
        city: "Ife",
    },
    {
        id: 18,
        Avatar: Room8 ,
        name:" Luxury room8 ",
        desc: "A well furnished Apartment that suite you",
        price: 15000,
        state: "Lagos",
        city: "Ajegunle",
    },
    {
        id: 19,
        Avatar: Room9 ,
        name:" Luxury room9 ",
        desc: "A well furnished Apartment that suite you",
        price: 15000,
        state: "Lagos",
        city: "Orile",
    },
    {
        id: 20,
        Avatar: Room10 ,
        name:" Luxury room10 ",
        desc: "A well furnished Apartment that suite you",
        price: 15000,
        state: "Lagos",
        city: "Amukoko",
    },
]
export default RoomData;